### ISSUE TITLE
Lisk install and Lisk.sh support for dynamic network upgrade

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-scripts#181]
Currently, `installLisk.sh` doesn't allow upgrade or install of `alphanet` network as the script is not compatible, it would be better if we can have a support for `install` or `upgrade` for any network `alpha, beta, testnet, mainnet` and custom network names `mynetwork`.

Note: `lisk.sh` also needs to be modified if we consider doing this change as it gets `blockchain.db` from the network path.

**Comment by fchavant** [comment]
Since release are now network-independent (but have a default network set in `env.sh`) we put them directly under downloads.lisk.io/lisk/.
- `installLisk.sh` would get the specified version (or the latest version) and use the specified network (or the default from the release)
- for `lisk.sh` we can keep `main/blockchain.db.gz` and `test/blockchain.db.gz`

**Comment by Nazgolze** [comment]
I could see doing this for installLisk.sh. It'd be easy to remove the network check in the case where you specify your own tar file

**Comment by Nazgolze** [comment]
Technically, we could build on the work that @pablitovicente did with changing log paths and change the pid path and even the app name in pm2-lisk.json.

Then if we change env.sh to set the network variable like this:
`export LISK_NETWORK=${LISK_NETWORK:testnet}` (or whatever default we want)
You could do thing something like this:
```NETWORKS=(alphanet betanet testnet mainnet devnet)
for network in ${NETWORKS[@]}; do
LISK_NETWORK=$network bash lisk.sh rebuild &
done
```
And have 5 instances of core running, one for each network.
Would have to be really careful with `coldstart` since it would nuke 5 databases

**Comment by fchavant** [comment]
Closing because commander will not support this.
