### ISSUE TITLE
lisk.sh status doesn't show correct block height

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-scripts#68]
### Expected behavior
`bash lisk.sh status` should show the correct block height, even when the node is sync'ing.

### Actual behavior
The logs show `block height 1` but `bash lisk.sh status` shows `block height 308694`

### Steps to reproduce
Rebuild node and do `bash lisk.sh status`

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0 beta 7

**Comment by Nazgolze** [comment]
Hi @punkr0ck. Ah, that's this issue: https://github.com/LiskHQ/lisk/issues/1914

So `bash lisk.sh status` reads directly from the db. What it shows is correct: it's showing the count of the blocks in the db. But the rebuild is verifying all of the blocks, so it rebuilds starting at the first block. That's why it shows `Rebuilding blockchain, current block height: 1`. It's the current block height in the rebuild process, not of the db. I can see how that would be confusing though

If you do `curl -s http://localhost:5000/api/blocks | jq .data[0].height` that should also show the correct block height and it should match `bash lisk.sh status`
